Autogenerated tree updates.
merged:

  flora: 523a446b976b43c4ede7fd49048643aaf4812e42
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  gentoo-staging-nov-2021: a15a64f48741a493e49dfee7d4280a3dc10cd21d
  kit-fixups: f657dcee54cac16e58517c36ac78bf3d84281fd6

diff --git a/sys-fs/zfs/templates/zfs.tmpl b/sys-fs/zfs/templates/zfs.tmpl
--- a/sys-fs/zfs/templates/zfs.tmpl
+++ b/sys-fs/zfs/templates/zfs.tmpl
@@ -70,6 +70,10 @@ REQUIRED_USE="
 
 RESTRICT="test"
 
+PATCHES=(
+	"${FILESDIR}"/zfs-LegacyVersion-ax_python_dev.patch
+)
+
 pkg_setup() {
 	if use kernel_linux && use test-suite; then
 		linux-info_pkg_setup
@@ -95,8 +99,8 @@ pkg_setup() {
 src_prepare() {
 	default
 
-# Set revision number
-sed -i "s/\(Release:\)\(.*\)1/\1\2${PR}-funtoo/" META || die "Could not set Gentoo release"
+	# Set revision number
+	sed -i "s/\(Release:\)\(.*\)1/\1\2${PR}-funtoo/" META || die "Could not set Gentoo release"
 
 	if use python; then
 		pushd contrib/pyzfs >/dev/null || die
@@ -107,6 +111,7 @@ sed -i "s/\(Release:\)\(.*\)1/\1\2${PR}-funtoo/" META || die "Could not set Gent
 	# prevent errors showing up on zfs-mount stop, #647688
 	# openrc will unmount all filesystems anyway.
 	sed -i "/^ZFS_UNMOUNT=/ s/yes/no/" "etc/default/zfs.in" || die
+	eautoreconf
 }
 
 src_configure() {
